drop table Agenda ;
drop table Calendar ;
drop table Book ;
drop table Photo ;
drop table Article ;
drop table Orders ;
drop table CodePromo;
drop table Image ;
drop table Contact ;
drop table Album ;
drop table Client ;
drop table Supply ;
drop table Prestataire ;
drop table Formats ;

drop sequence IdIdSupply;
drop sequence IdArticle;
drop sequence IdOrders;
drop sequence IdCodePromo;
drop sequence IdImage;
drop sequence IdAlbum;
drop sequence IdClient;
drop sequence IdPrestataire;
drop sequence IdFormats;
